name: Automerge replit-dev → main (fast-forward only)

on:
  push:
    branches: [ replit-dev ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ffmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # We’ll push ourselves; disable default creds to allow PAT fallback if needed
          persist-credentials: false

      - name: Configure git author
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch branches
        run: |
          git fetch origin main replit-dev

      - name: Fast-forward main to replit-dev
        run: |
          set -e
          git checkout -B main origin/main
          # Fast-forward only (no merge commits). Fails if histories diverged.
          git merge --ff-only origin/replit-dev

      - name: Push to main (GITHUB_TOKEN)
        id: push_gh_token
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git"
          git push origin main

      - name: Push to main (PAT fallback)
        if: steps.push_gh_token.outcome == 'failure' && secrets.GH_PAT != ''
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -e
          git remote set-url origin "https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git"
          git push origin main
