name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

env:
  DEPLOY_SSH_USER:         ${{ secrets.SSH_USER }}
  DEPLOY_SSH_HOST:         ${{ secrets.SSH_HOST }}
  DEPLOY_SSH_PORT:         ${{ secrets.SSH_PORT }}
  DEPLOY_APP_PATH:         ${{ secrets.APP_PATH }}
  PM2_APP:                 ${{ secrets.PM2_APP }}
  CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID }}
  CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  CF_API_TOKEN:            ${{ secrets.CF_API_TOKEN }}
  CF_ZONE_ID:              ${{ secrets.CF_ZONE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Load your private key into ssh-agent (avoids heredoc/newline issues)
      - name: Use SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust remote host key
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_SSH_HOST:?missing}"; : "${DEPLOY_SSH_PORT:?missing}"
          ssh-keyscan -p "$DEPLOY_SSH_PORT" "$DEPLOY_SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Sync files to server (rsync over SSH)
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_SSH_USER:?missing}"; : "${DEPLOY_SSH_HOST:?missing}"; : "${DEPLOY_SSH_PORT:?missing}"; : "${DEPLOY_APP_PATH:?missing}"
          rsync -az --delete \
            --rsh="ssh -p $DEPLOY_SSH_PORT -o StrictHostKeyChecking=yes" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            --exclude "*.log" \
            ./ "$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST:$DEPLOY_APP_PATH/"

      - name: Remote build & restart with PM2
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_SSH_USER:?missing}"; : "${DEPLOY_SSH_HOST:?missing}"; : "${DEPLOY_SSH_PORT:?missing}"; : "${DEPLOY_APP_PATH:?missing}"; : "${PM2_APP:?missing}"
          ssh -p "$DEPLOY_SSH_PORT" -o StrictHostKeyChecking=yes "$DEPLOY_SSH_USER@$DEPLOY_SSH_HOST" /bin/bash -lc '
            set -euo pipefail
            cd "'"$DEPLOY_APP_PATH"'"

            echo "[Deploy] Node & npm versions:"
            command -v node && node -v || true
            command -v npm && npm -v || true

            echo "[Deploy] Installing dependencies…"
            npm ci

            echo "[Deploy] Building…"
            export CF_ACCESS_CLIENT_ID="'"$CF_ACCESS_CLIENT_ID"'"
            export CF_ACCESS_CLIENT_SECRET="'"$CF_ACCESS_CLIENT_SECRET"'"
            export CF_API_TOKEN="'"$CF_API_TOKEN"'"
            export CF_ZONE_ID="'"$CF_ZONE_ID"'"
            npm run build

            echo "[Deploy] Reloading PM2 app…"
            if pm2 status "'"$PM2_APP"'" >/dev/null 2>&1; then
              pm2 reload "'"$PM2_APP"'"
            else
              pm2 start dist/index.js --name "'"$PM2_APP"'"
            fi
            pm2 save
          '
