name: Deploy FrostLine (SIMPLE)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: deploy-frostline-simple-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust server host key
        shell: bash
        run: |
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Connectivity test
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes -o PreferredAuthentications=publickey -o BatchMode=yes \
            "$SSH_USER@$SSH_HOST" 'echo OK $(hostname); whoami'

      - name: Bootstrap server (Node 20, PM2, tools)
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y ca-certificates curl gnupg rsync git build-essential python3 pkg-config jq age
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2
            fi
            mkdir -p /var/www/frostline
            node -v; npm -v; pm2 -v
          '

      - name: Rsync code to /var/www/frostline
        shell: bash
        run: |
          rsync -az --delete \
            --rsh="ssh -4 -p $SSH_PORT -o StrictHostKeyChecking=yes -o PreferredAuthentications=publickey -o BatchMode=yes" \
            --exclude ".git/" --exclude ".github/" --exclude "node_modules/" --exclude "*.log" \
            ./ "$SSH_USER@$SSH_HOST:/var/www/frostline/"

      - name: Ensure robust PM2 wrapper (PORT=5000 + safe fallbacks)
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            sudo mkdir -p /root/pm2
            printf "%s\n" \
              "#!/usr/bin/env bash" \
              "set -euo pipefail" \
              "cd /var/www/frostline" \
              'if [ -f ./.env.age ]; then set -a; source <(age -d -i /root/.config/age/keys.txt ./.env.age); set +a; fi' \
              'export PORT="${PORT:-5000}"' \
              'export NODE_ENV="${NODE_ENV:-production}"' \
              'export SENDGRID_API_KEY="${SENDGRID_API_KEY:-disabled}"' \
              'export AUTHORIZE_NET_API_LOGIN_ID="${AUTHORIZE_NET_API_LOGIN_ID:-disabled}"' \
              'export AUTHORIZE_NET_TRANSACTION_KEY="${AUTHORIZE_NET_TRANSACTION_KEY:-disabled}"' \
              'export ALGOLIA_APP_ID="${ALGOLIA_APP_ID:-disabled}"' \
              'export ALGOLIA_ADMIN_API_KEY="${ALGOLIA_ADMIN_API_KEY:-disabled}"' \
              'export ZOHO_ACCOUNTS_HOST="${ZOHO_ACCOUNTS_HOST:-https://accounts.zoho.com}"' \
              'export ZOHO_CRM_BASE="${ZOHO_CRM_BASE:-https://www.zohoapis.com/crm}"' \
              'export ZOHO_REDIRECT_URI="${ZOHO_REDIRECT_URI:-https://localhost/zoho/callback}"' \
              "exec node dist/index.js" \
            | sudo tee /root/pm2/start-frostline.sh >/dev/null
            sudo chmod +x /root/pm2/start-frostline.sh
          '

      - name: Build & restart with PM2 (inject DB + RSR FTP)
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            cd /var/www/frostline
            export NPM_CONFIG_FUND=false NPM_CONFIG_AUDIT=false
            npm ci
            npm run build

            # Runtime env (always bind on :5000)
            export PORT=5000 NODE_ENV=production
            export DATABASE_URL='"'"'${{ secrets.DATABASE_URL }}'"'"'
            export RSR_FTP_HOST='"'"'${{ secrets.RSR_FTP_HOST }}'"'"'
            export RSR_USERNAME='"'"'${{ secrets.RSR_USERNAME }}'"'"'
            export RSR_PASSWORD='"'"'${{ secrets.RSR_PASSWORD }}'"'"'
            # (STANDARD creds optional; not used for FTP login)
            [ -n "'"${{ secrets.RSR_STANDARD_USERNAME }}"'" ] && export RSR_STANDARD_USERNAME='"'"'${{ secrets.RSR_STANDARD_USERNAME }}'"'"' || true
            [ -n "'"${{ secrets.RSR_STANDARD_PASSWORD }}"'" ] && export RSR_STANDARD_PASSWORD='"'"'${{ secrets.RSR_STANDARD_PASSWORD }}'"'"' || true

            pm2 delete frostline >/dev/null 2>&1 || true
            pm2 start /root/pm2/start-frostline.sh --name frostline --cwd /var/www/frostline --update-env
            pm2 save
          '
