name: Deploy (main)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Frostline server
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          APP_PATH: ${{ secrets.APP_PATH }}
          PM2_APP: ${{ secrets.PM2_APP }}
          GIT_URL: ${{ secrets.GIT_URL }}
        run: |
          set -e
          echo "Deploying to $SSH_USER@$SSH_HOST:$SSH_PORT ..."
          ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -s << 'EOSH'
          set -e
          mkdir -p "$APP_PATH"
          if [ ! -d "$APP_PATH/.git" ]; then
            git clone "$GIT_URL" "$APP_PATH"
          fi
          cd "$APP_PATH"
          git pull --ff-only || true

          # Install Node.js if missing
          if ! command -v node >/dev/null 2>&1; then
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
            apt-get install -y nodejs
          fi

          npm ci --omit=dev
          npm run build

          # Install PM2 if missing, then reload/start app
          if ! command -v pm2 >/dev/null 2>&1; then
            npm install -g pm2
          fi
          pm2 describe "$PM2_APP" >/dev/null 2>&1 && pm2 reload "$PM2_APP" || pm2 start dist/index.js --name "$PM2_APP"
          pm2 save
          EOSH
