name: Deploy FrostLine

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          set -euo pipefail
          test -n "${{ secrets.SSH_KEY }}"      || { echo "::error::SSH_KEY is empty"; exit 1; }
          test -n "${SSH_HOST}"                 || { echo "::error::SSH_HOST is empty"; exit 1; }
          test -n "${SSH_USER}"                 || { echo "::error::SSH_USER is empty"; exit 1; }
          test -n "${SSH_PORT}"                 || { echo "::error::SSH_PORT is empty"; exit 1; }
          test -n "${{ secrets.DATABASE_URL }}" || { echo "::error::DATABASE_URL is empty"; exit 1; }
          test -n "${{ secrets.RSR_USERNAME }}" || { echo "::error::RSR_USERNAME is empty"; exit 1; }
          test -n "${{ secrets.RSR_PASSWORD }}" || { echo "::error::RSR_PASSWORD is empty"; exit 1; }
          if [ -z "${{ secrets.INVENTORY_ORIGIN }}" ] && [ -z "${{ secrets.INVENTORY_DEV_PUBLIC_URL }}" ]; then
            echo "::error::INVENTORY_ORIGIN or INVENTORY_DEV_PUBLIC_URL must be set"; exit 1;
          fi

      - name: Start ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Smoke test SSH
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo ok && whoami && hostname"

      - name: Push env + restart script and run
        env:
          DATABASE_URL:  ${{ secrets.DATABASE_URL }}
          RSR_USERNAME:  ${{ secrets.RSR_USERNAME }}
          RSR_PASSWORD:  ${{ secrets.RSR_PASSWORD }}
          RSR_FTP_HOST:  ${{ secrets.RSR_FTP_HOST }}
          RSR_FTP_PORT:  ${{ secrets.RSR_FTP_PORT }}
          RSR_FTPS:      ${{ secrets.RSR_FTPS }}

          RSR_STANDARD_USERNAME: ${{ secrets.RSR_STANDARD_USERNAME }}
          RSR_STANDARD_PASSWORD: ${{ secrets.RSR_STANDARD_PASSWORD }}

          AUTHORIZE_NET_API_LOGIN_ID:    ${{ secrets.AUTHORIZE_NET_API_LOGIN_ID }}
          AUTHORIZE_NET_TRANSACTION_KEY: ${{ secrets.AUTHORIZE_NET_TRANSACTION_KEY }}
          SENDGRID_API_KEY:              ${{ secrets.SENDGRID_API_KEY }}

          # Algolia — exact names (include SEARCH + ADMIN keys)
          ALGOLIA_APP_ID:        ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY:       ${{ secrets.ALGOLIA_API_KEY }}        # search key (may be blank)
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}  # admin key
          ALGOLIA_ADMIN_KEY:     ${{ secrets.ALGOLIA_ADMIN_KEY }}      # alias (optional)

          # API base + auth header
          INVENTORY_ORIGIN:         ${{ secrets.INVENTORY_ORIGIN }}
          INVENTORY_DEV_PUBLIC_URL: ${{ secrets.INVENTORY_DEV_PUBLIC_URL }}
          SERVICE_KEY:              ${{ secrets.SERVICE_KEY }}
          SERVICE_KEY_HEADER:       ${{ secrets.SERVICE_KEY_HEADER }}
        run: |
          set -euo pipefail

          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'install -d -m 700 /root/pm2'

          # Compute effective values for keys that may be unset
          SEARCH_EFFECTIVE="${ALGOLIA_API_KEY:-}"
          ADMIN_EFFECTIVE="${ALGOLIA_ADMIN_API_KEY:-${ALGOLIA_ADMIN_KEY:-}}"
          if [ -z "${SEARCH_EFFECTIVE}" ]; then
            SEARCH_EFFECTIVE="${ADMIN_EFFECTIVE}"
          fi

          envfile="$(mktemp)"; umask 077
          {
            echo "PORT=5000"
            echo "NODE_ENV=production"
            echo "DATABASE_URL=${DATABASE_URL}"

            echo "RSR_FTP_HOST=${RSR_FTP_HOST:-ftps.rsrgroup.com}"
            echo "RSR_FTP_PORT=${RSR_FTP_PORT:-2222}"
            echo "RSR_PORT=${RSR_FTP_PORT:-2222}"
            echo "RSR_FTPS=${RSR_FTPS:-1}"
            echo "RSR_USERNAME=${RSR_USERNAME}"
            echo "RSR_PASSWORD=${RSR_PASSWORD}"
            [ -n "${RSR_STANDARD_USERNAME:-}" ] && echo "RSR_STANDARD_USERNAME=${RSR_STANDARD_USERNAME}"
            [ -n "${RSR_STANDARD_PASSWORD:-}" ] && echo "RSR_STANDARD_PASSWORD=${RSR_STANDARD_PASSWORD}"

            [ -n "${AUTHORIZE_NET_API_LOGIN_ID:-}" ] && echo "AUTHORIZE_NET_API_LOGIN_ID=${AUTHORIZE_NET_API_LOGIN_ID}"
            [ -n "${AUTHORIZE_NET_TRANSACTION_KEY:-}" ] && echo "AUTHORIZE_NET_TRANSACTION_KEY=${AUTHORIZE_NET_TRANSACTION_KEY}"
            [ -n "${SENDGRID_API_KEY:-}" ] && echo "SENDGRID_API_KEY=${SENDGRID_API_KEY}"

            # Algolia — write SEARCH + ADMIN keys
            [ -n "${ALGOLIA_APP_ID:-}" ] && echo "ALGOLIA_APP_ID=${ALGOLIA_APP_ID}"
            [ -n "${ADMIN_EFFECTIVE:-}" ] && { echo "ALGOLIA_ADMIN_API_KEY=${ADMIN_EFFECTIVE}"; echo "ALGOLIA_ADMIN_KEY=${ADMIN_EFFECTIVE}"; }
            [ -n "${SEARCH_EFFECTIVE:-}" ] && echo "ALGOLIA_API_KEY=${SEARCH_EFFECTIVE}"

            # API base
            INV="${INVENTORY_ORIGIN:-${INVENTORY_DEV_PUBLIC_URL:-}}"
            echo "INVENTORY_ORIGIN=${INV}"

            # Auth header for upstream, if used
            [ -n "${SERVICE_KEY_HEADER:-}" ] && echo "SERVICE_KEY_HEADER=${SERVICE_KEY_HEADER}"
            [ -n "${SERVICE_KEY:-}" ] && echo "SERVICE_KEY=${SERVICE_KEY}"

            echo "REQUIRE_PRODUCTS=0"
          } > "$envfile"

          [ -f "scripts/restart.sh" ] || { echo "::error::scripts/restart.sh missing in repo"; rm -f "$envfile"; exit 1; }

          scp -P "$SSH_PORT" "$envfile" "$SSH_USER@$SSH_HOST:/root/pm2/frostline.env"
          scp -P "$SSH_PORT" "scripts/restart.sh" "$SSH_USER@$SSH_HOST:/root/pm2/restart.sh"
          rm -f "$envfile"

          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" bash -se << 'EOF'
          set -euo pipefail
          chmod 700 /root/pm2/restart.sh
          /root/pm2/restart.sh

          # Non-fatal probes (for quick visibility)
          set +e
          . /root/pm2/frostline.env 2>/dev/null
          HDR=()
          if [ -n "${SERVICE_KEY_HEADER:-}" ] && [ -n "${SERVICE_KEY:-}" ]; then
            HDR+=(--header "$(printf '%s: %s' "$SERVICE_KEY_HEADER" "$SERVICE_KEY")")
          fi
          echo "Probe 1: ${INVENTORY_ORIGIN%/}/api/firearms-compliance/config"
          curl -ksS -o /root/pm2/probe1.json -w "\nHTTP:%{http_code} CT:%{content_type}\n" -H "Accept: application/json" "${HDR[@]}" "${INVENTORY_ORIGIN%/}/api/firearms-compliance/config"
          head -c 200 /root/pm2/probe1.json; echo

          echo "Probe 2: ${INVENTORY_ORIGIN%/}/api/products?limit=1"
          curl -ksS -o /root/pm2/probe2.json -w "\nHTTP:%{http_code} CT:%{content_type}\n" -H "Accept: application/json" "${HDR[@]}" "${INVENTORY_ORIGIN%/}/api/products?limit=1"
          head -c 200 /root/pm2/probe2.json; echo
          set -e
          EOF
