name: Deploy FrostLine (SIMPLE)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: deploy-frostline-simple-${{ github.ref_name }}
  cancel-in-progress: true

env:
  SSH_USER: ${{ secrets.SSH_USER }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load SSH key into agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust server host key
        shell: bash
        run: |
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Connectivity test
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes -o PreferredAuthentications=publickey -o BatchMode=yes \
            "$SSH_USER@$SSH_HOST" 'echo OK $(hostname); whoami'

      - name: Bootstrap server (Node 20, PM2, tools) and ensure path
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y ca-certificates curl gnupg rsync git build-essential python3 pkg-config jq
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2
            fi
            mkdir -p /var/www/frostline
            node -v; npm -v; pm2 -v
          '

      - name: Sync files to /var/www/frostline
        shell: bash
        run: |
          rsync -az --delete \
            --rsh="ssh -4 -p $SSH_PORT -o StrictHostKeyChecking=yes -o PreferredAuthentications=publickey -o BatchMode=yes" \
            --exclude ".git/" --exclude ".github/" --exclude "node_modules/" --exclude "*.log" \
            ./ "$SSH_USER@$SSH_HOST:/var/www/frostline/"

      - name: Ensure PM2 wrapper exists (no server env files)
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            sudo mkdir -p /root/pm2
            printf "%s\n" \
              "#!/usr/bin/env bash" \
              "set -euo pipefail" \
              "cd /var/www/frostline" \
              "exec node dist/index.js" \
            | sudo tee /root/pm2/start-frostline.sh >/dev/null
            sudo chmod +x /root/pm2/start-frostline.sh
          '

      - name: Build & restart with PM2 (inject only DATABASE_URL)
        shell: bash
        run: |
          ssh -4 -p "$SSH_PORT" -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" /bin/bash -lc 'set -e
            cd /var/www/frostline
            export NPM_CONFIG_FUND=false NPM_CONFIG_AUDIT=false
            npm ci
            npm run build
            # Start via wrapper; pass just DB from GH; no files written
            export PORT=5001 NODE_ENV=production DATABASE_URL='"'"'${{ secrets.DATABASE_URL }}'"'"'
            pm2 delete frostline >/dev/null 2>&1 || true
            pm2 start /root/pm2/start-frostline.sh --name frostline --cwd /var/www/frostline --update-env
            pm2 save
          '
