name: deploy-inventory

on:
  push:
    branches: [prod]
    paths:
      - 'services/inventory/**'
      - '.github/workflows/deploy-inventory.yml'
  workflow_dispatch:

jobs:
  apply-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Guardrail: fail if required config files are missing
      - name: Verify Algolia config files exist
        run: |
          test -s services/inventory/algolia/catalog/settings.json
          test -s services/inventory/algolia/catalog/rules.json
          test -s services/inventory/algolia/catalog/synonyms.json

      # Apply settings/rules/synonyms from repo to target index
      - name: Apply Algolia config
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
        run: |
          BASE="https://${ALGOLIA_APP_ID}-dsn.algolia.net/1/indexes/${ALGOLIA_INDEX}"
          HDRS=(-H "X-Algolia-Application-Id: ${ALGOLIA_APP_ID}" -H "X-Algolia-API-Key: ${ALGOLIA_ADMIN_KEY}" -H "Content-Type: application/json")

          curl -sS -X PUT  "${HDRS[@]}" "$BASE/settings"        --data-binary @services/inventory/algolia/catalog/settings.json
          curl -sS -X POST "${HDRS[@]}" "$BASE/rules/batch"     --data-binary @services/inventory/algolia/catalog/rules.json
          curl -sS -X POST "${HDRS[@]}" "$BASE/synonyms/batch"  --data-binary @services/inventory/algolia/catalog/synonyms.json

      # TODO: add your existing inventory deploy step(s) here
      - name: Deploy inventory
        run: |
          echo "Deploying inventory service..."
          # ssh / docker / coolify / etc.