name: Deploy FrostLine

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          test -n "${{ secrets.SSH_KEY }}"   || { echo "::error::SSH_KEY is empty"; exit 1; }
          test -n "${SSH_HOST}"              || { echo "::error::SSH_HOST is empty"; exit 1; }
          test -n "${SSH_USER}"              || { echo "::error::SSH_USER is empty"; exit 1; }
          test -n "${SSH_PORT}"              || { echo "::error::SSH_PORT is empty"; exit 1; }

      - name: Start ssh-agent (load private key)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Smoke test SSH
        run: ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'echo ok; whoami; hostname'

      # Add your deploy steps below this line
      # - name: Deploy
      #   run: |
      #     ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'bash -s' <<'SH'
      #     set -euo pipefail
      #     cd /var/www/frostline
      #     pm2 restart frostline --update-env --cwd /var/www/frostline
      #     pm2 save
      #     SH
