name: Deploy FrostLine

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: |
          set -euo pipefail
          test -n "${{ secrets.SSH_KEY }}"       || { echo "::error::SSH_KEY is empty"; exit 1; }
          test -n "${SSH_HOST}"                  || { echo "::error::SSH_HOST is empty"; exit 1; }
          test -n "${SSH_USER}"                  || { echo "::error::SSH_USER is empty"; exit 1; }
          test -n "${SSH_PORT}"                  || { echo "::error::SSH_PORT is empty"; exit 1; }
          test -n "${{ secrets.DATABASE_URL }}"  || { echo "::error::DATABASE_URL is empty"; exit 1; }
          test -n "${{ secrets.RSR_USERNAME }}"  || { echo "::error::RSR_USERNAME (FTP) is empty"; exit 1; }
          test -n "${{ secrets.RSR_PASSWORD }}"  || { echo "::error::RSR_PASSWORD (FTP) is empty"; exit 1; }

      - name: Start ssh-agent (load private key)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SSH_PORT" -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Smoke test SSH
        run: |
          set -euo pipefail
          ssh -o BatchMode=yes -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'echo ok && whoami && hostname'

      - name: Write env and restart PM2 (safe, idempotent)
        env:
          # Required
          DATABASE_URL:                  ${{ secrets.DATABASE_URL }}
          RSR_USERNAME:                  ${{ secrets.RSR_USERNAME }}
          RSR_PASSWORD:                  ${{ secrets.RSR_PASSWORD }}

          # Recommended defaults (overridable)
          RSR_FTP_HOST:                  ${{ secrets.RSR_FTP_HOST }}
          RSR_FTP_PORT:                  ${{ secrets.RSR_FTP_PORT }}
          RSR_FTPS:                      ${{ secrets.RSR_FTPS }}

          # RSR “Standard” (API/feed) – distinct from FTP (optional)
          RSR_STANDARD_USERNAME:         ${{ secrets.RSR_STANDARD_USERNAME }}
          RSR_STANDARD_PASSWORD:         ${{ secrets.RSR_STANDARD_PASSWORD }}

          # Optional integrations
          AUTHORIZE_NET_API_LOGIN_ID:    ${{ secrets.AUTHORIZE_NET_API_LOGIN_ID }}
          AUTHORIZE_NET_TRANSACTION_KEY: ${{ secrets.AUTHORIZE_NET_TRANSACTION_KEY }}
          SENDGRID_API_KEY:              ${{ secrets.SENDGRID_API_KEY }}
          ALGOLIA_APP_ID:                ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY:         ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: |
          set -euo pipefail

          # Ensure remote folder exists (private perms)
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'install -d -m 700 /root/pm2'

          # Build a temp .env locally (masked in logs)
          envfile="$(mktemp)"; umask 077
          {
            printf 'PORT=5000\n'
            printf 'NODE_ENV=production\n'
            printf 'DATABASE_URL=%s\n' "$DATABASE_URL"
            # --- RSR FTPS (explicit TLS on 2222) ---
            printf 'RSR_FTP_HOST=%s\n' "${RSR_FTP_HOST:-ftps.rsrgroup.com}"
            printf 'RSR_FTP_PORT=%s\n' "${RSR_FTP_PORT:-2222}"
            printf 'RSR_FTPS=%s\n'     "${RSR_FTPS:-1}"
            # FTP creds ONLY (dealer login)
            printf 'RSR_USERNAME=%s\n' "$RSR_USERNAME"
            printf 'RSR_PASSWORD=%s\n' "$RSR_PASSWORD"
            # --- RSR "Standard" feed/API creds (separate from FTP) ---
            if [ -n "${RSR_STANDARD_USERNAME:-}" ]; then printf 'RSR_STANDARD_USERNAME=%s\n' "$RSR_STANDARD_USERNAME"; fi
            if [ -n "${RSR_STANDARD_PASSWORD:-}" ]; then printf 'RSR_STANDARD_PASSWORD=%s\n' "$RSR_STANDARD_PASSWORD"; fi
            # Optional integrations
            if [ -n "${AUTHORIZE_NET_API_LOGIN_ID:-}" ];    then printf 'AUTHORIZE_NET_API_LOGIN_ID=%s\n' "$AUTHORIZE_NET_API_LOGIN_ID"; fi
            if [ -n "${AUTHORIZE_NET_TRANSACTION_KEY:-}" ]; then printf 'AUTHORIZE_NET_TRANSACTION_KEY=%s\n' "$AUTHORIZE_NET_TRANSACTION_KEY"; fi
            if [ -n "${SENDGRID_API_KEY:-}" ];              then printf 'SENDGRID_API_KEY=%s\n' "$SENDGRID_API_KEY"; fi
            if [ -n "${ALGOLIA_APP_ID:-}" ];                then printf 'ALGOLIA_APP_ID=%s\n' "$ALGOLIA_APP_ID"; fi
            if [ -n "${ALGOLIA_ADMIN_API_KEY:-}" ];         then printf 'ALGOLIA_ADMIN_API_KEY=%s\n' "$ALGOLIA_ADMIN_API_KEY"; fi
          } >"$envfile"

          # Ship env file
          scp -P "$SSH_PORT" "$envfile" "$SSH_USER@$SSH_HOST:/root/pm2/frostline.env"
          rm -f "$envfile"

          # Create the remote restart script with a single-quoted heredoc (no interpolation here)
          restart="$(mktemp)"; umask 077
          cat >"$restart" <<'SCRIPT'
#!/usr/bin/env bash
set -euo pipefail
set +H

chmod 600 /root/pm2/frostline.env
set -a; . /root/pm2/frostline.env; set +a

# -------- Parse DATABASE_URL without sed/awk (safe shell) --------
DBURL="$DATABASE_URL"
DB_NO_SCHEME="${DBURL#*://}"

DB_USER="${DB_NO_SCHEME%%:*}"            # before first :
REST="${DB_NO_SCHEME#*:}"
DB_PASS="${REST%%@*}"                    # before @

REST="${DB_NO_SCHEME#*@}"
DB_HOST="${REST%%/*}"                    # host[:port]
DB_HOST="${DB_HOST%%:*}"                 # strip :port if present

DB_NAME="${DBURL##*/}"                   # after last /
DB_NAME="${DB_NAME%%\?*}"                # strip ?query if present

# Escape single-quotes for SQL
ESC_PASS="${DB_PASS//\'/\'\'}"

# -------- Ensure role/db exist; set password to match secret --------
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '$DB_USER') THEN CREATE ROLE \"$DB_USER\" LOGIN PASSWORD '$ESC_PASS'; END IF; END \$\$;"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "ALTER ROLE \"$DB_USER\" WITH LOGIN PASSWORD '$ESC_PASS';"
sudo -u postgres psql -v ON_ERROR_STOP=1 -c "DO \$\$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '$DB_NAME') THEN CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\"; END IF; END \$\$;"

# Connectivity check as the app user
PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -Atqc "select 1" >/dev/null

# -------- Best-effort backup (no subshell/paren tricks) --------
if command -v pg_dump >/dev/null 2>&1; then
  ts="$(date +%Y%m%d-%H%M%S)"
  install -d -m 700 /root/backups
  if ! PGPASSWORD="$DB_PASS" pg_dump -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" --no-owner --format=custom -f "/root/backups/frostline-$ts.dump"; then
    echo "::warning::pg_dump failed - backup skipped"
  fi
fi

# -------- Restart app & persist --------
cd /var/www/frostline
pm2 restart frostline --update-env --cwd /var/www/frostline
pm2 save

# Wait up to 30s for :5000
for i in {1..30}; do
  if ss -ltnp | grep -qE ':5000\b'; then break; fi
  sleep 1
done
ss -ltnp | grep -E ':5000\b' >/dev/null || { echo "::error::app is not listening on :5000"; exit 1; }

# Origins
curl -fsSI http://127.0.0.1:5000/ | head -1 || true
if command -v nginx >/dev/null 2>&1; then
  curl -fsSI -H "Host: thegunfirm.com" http://127.0.0.1/ | head -1 || true
fi

# RSR FTPS handshake & status
pm2 logs frostline --lines 200 --nostream | egrep -i 'Connecting FTPS|> USER|< 331|< 230|< 530|IM-QTY|FULL|download|insert|upsert|error' || true

# Kick a full import (best-effort)
pm2 trigger frostline rsr:full >/dev/null 2>&1 || \
  curl -fsS -X POST http://127.0.0.1:5000/_internal/rsr/full >/dev/null 2>&1 || true
SCRIPT

          # Ship & execute the restart script
          scp -P "$SSH_PORT" "$restart" "$SSH_USER@$SSH_HOST:/root/pm2/restart.sh"
          rm -f "$restart"
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" 'bash /root/pm2/restart.sh'
