name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref_name }}
  cancel-in-progress: true

env:
  DEPLOY_APP_PATH:         ${{ secrets.APP_PATH }}
  PM2_APP:                 ${{ secrets.PM2_APP }}
  CF_ACCESS_CLIENT_ID:     ${{ secrets.CF_ACCESS_CLIENT_ID }}
  CF_ACCESS_CLIENT_SECRET: ${{ secrets.CF_ACCESS_CLIENT_SECRET }}
  CF_API_TOKEN:            ${{ secrets.CF_API_TOKEN }}
  CF_ZONE_ID:              ${{ secrets.CF_ZONE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (main)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load SSH key into agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Trust server host key (IPv4)
        shell: bash
        run: |
          set -euo pipefail
          ssh-keyscan -4 -p 22 5.78.137.95 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Connectivity test (root@5.78.137.95)
        shell: bash
        run: |
          set -euo pipefail
          ssh -4 -p 22 \
            -o StrictHostKeyChecking=yes \
            -o PreferredAuthentications=publickey \
            -o BatchMode=yes \
            root@5.78.137.95 'echo OK $(hostname); whoami'

      - name: Bootstrap server (Node 20, PM2, tools) and ensure path
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_APP_PATH:?missing}"
          ssh -4 -p 22 -o StrictHostKeyChecking=yes root@5.78.137.95 /bin/bash -lc '
            set -e
            export DEBIAN_FRONTEND=noninteractive
            apt-get update -y
            apt-get install -y ca-certificates curl gnupg rsync git build-essential python3 pkg-config
            if ! command -v node >/dev/null 2>&1; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
              apt-get install -y nodejs
            fi
            if ! command -v pm2 >/dev/null 2>&1; then
              npm i -g pm2
            fi
            mkdir -p "'"$DEPLOY_APP_PATH"'"
            echo "[Versions]"; node -v; npm -v; pm2 -v
          '

      - name: Sync files to server (rsync over SSH)
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_APP_PATH:?missing}"
          rsync -az --delete \
            --rsh="ssh -4 -p 22 -o StrictHostKeyChecking=yes -o PreferredAuthentications=publickey -o BatchMode=yes" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            --exclude "*.log" \
            ./ root@5.78.137.95:"$DEPLOY_APP_PATH/"

      - name: Remote build & restart with PM2
        shell: bash
        run: |
          set -euo pipefail
          : "${DEPLOY_APP_PATH:?missing}"
          ssh -4 -p 22 -o StrictHostKeyChecking=yes root@5.78.137.95 /bin/bash -lc '
            set -euo pipefail
            cd "'"$DEPLOY_APP_PATH"'"

            export NPM_CONFIG_FUND=false NPM_CONFIG_AUDIT=false
            command -v node && node -v || true
            command -v npm && npm -v || true

            npm ci
            export CF_ACCESS_CLIENT_ID="'"$CF_ACCESS_CLIENT_ID"'"
            export CF_ACCESS_CLIENT_SECRET="'"$CF_ACCESS_CLIENT_SECRET"'"
            export CF_API_TOKEN="'"$CF_API_TOKEN"'"
            export CF_ZONE_ID="'"$CF_ZONE_ID"'"
            npm run build

            APP_NAME="${PM2_APP:-frostline}"
            if pm2 describe "$APP_NAME" >/dev/null 2>&1; then
              pm2 reload "$APP_NAME"
            else
              pm2 start dist/index.js --name "$APP_NAME"
            fi
            # make PM2 restart on reboot
            pm2 save
            pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
          '
