name: RSR → Hetzner Image Sync

on:
  schedule:
    - cron: "*/15 * * * *"   # run every 15 minutes
  workflow_dispatch:         # allow manual trigger from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install runtime deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i @aws-sdk/client-s3 basic-ftp mime

      - name: Run sync script
        env:
          RSR_FTP_HOST: ${{ secrets.RSR_FTP_HOST }}
          RSR_FTP_USER: ${{ secrets.RSR_FTP_USER }}
          RSR_FTP_PASS: ${{ secrets.RSR_FTP_PASS }}
          HETZNER_S3_ENDPOINT: ${{ secrets.HETZNER_S3_ENDPOINT }}
          HETZNER_S3_REGION: ${{ secrets.HETZNER_S3_REGION }}
          HETZNER_S3_BUCKET: ${{ secrets.HETZNER_S3_BUCKET }}
          HETZNER_S3_ACCESS_KEY: ${{ secrets.HETZNER_S3_ACCESS_KEY }}
          HETZNER_S3_SECRET_KEY: ${{ secrets.HETZNER_S3_SECRET_KEY }}
        run: node scripts/sync-rsr-to-hetzner.mjs
